# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://origin.seamlessaccess.org/'
baseurl: ''
title: 'SA Site'
description: 'SeamlessAccess'
permalink: pretty
logo: "/assets/img/brand/SeamlessAccess-Logo_Blue_50.png"

# Pagination
paginate: 5
paginate_path: news-events/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: What is Seamless Access?
  url: /about/
- title: FAQ
  url: /FAQ/
- title: News & Events
  url: /news-events/
- title: Get Started
  url: /get-started/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: News & Events
    output: true
    description: "Stay up to date on Seamless Access news and events."
    feature_text:
    feature_image: "https://picsum.photos/2560/600?image=866"

# Front Matter generator
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
