# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://origin.seamlessaccess.org/'
baseurl: ''
title: 'SA Site'
description: 'This is a new website'
permalink: pretty
logo: "/assets/images/style/SeamlessAccess-Logo_Blue_50.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: News & Events
  url: /news-events/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: News & events
    output: true
    description: "Stay up to date on Seamless Access news and events."
    feature_text: |
      Hero Text
    feature_image: "https://picsum.photos/2560/600?image=866"
