source "https://rubygems.org"
gem 'github-pages', group: :jekyll_plugins
gem "jekyll"
gem "jekyll-sitemap"
gem "jekyll-mentions"
gem "jekyll-paginate"
gem "jekyll-seo-tag"
gem "jekyll-redirect-from"
gem "jekyll-default-layout"
gem "jekyll-feed"
gem "jemoji"
gem "jekyll-remote-theme"